[phases.setup]
nixPkgs = ['python311', 'gcc', 'libffi', 'cargo', 'rustc']

[phases.install]
cmds = [
  'pip install --upgrade pip setuptools wheel',
  'pip install -r requirements.txt --no-cache-dir'
]

[start]
cmd = 'python main.py'
