services:
  - type: worker
    name: telegram-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install --upgrade pip && pip install --only-binary=:all: -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: YOUR_TELEGRAM
        sync: false
